spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiaxiangwei?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
   #Redis数据库索引
    database: 0
    #redis服务器地址
    host: 127.0.0.1
    #服务器连接端口号
    port: 6379
    #服务器连接密码
    password: 123456
    pool:
      #连接池最大连接数（负数标示没限制）
      max-active: 200
      #连接池最大等待时间（负数标示没限制）
      max-wait: 3600
      #连接池最大空闲连接
      max-idle: 10
      #连接池最小空闲连接
      min-idle: 0
      #连接超时时间（毫秒）
    timeout: 1000
  #关闭工作流异步任务的定时执行
  activiti:
    async-executor-enabled: false
    job-executor-activate: false
mybatis:
  mapper-locations: classpath:com/shuanghui/jiaxiangwei/mapper/*.xml
  type-aliases-package: com.shuanghui.jiaxiangwei.dto
server:
  port: 8080