spring:
  thymeleaf:
   prefix: classpath:/templates/
   cache: false
  #引入的外部文件，前缀是 application
  profiles:
    include: directory
  datasource:
    url: jdbc:mysql://localhost:3306/jiaxiangwei?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
   #静态资源直接访问
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
mybatis:
  mapper-locations: classpath:com/shuanghui/jiaxiangwei/mapper/*.xml
  type-aliases-package: com.shuanghui.jiaxiangwei.dto
